"""Typings for queries generated by aiosql"""

from typing import Dict, Optional, Sequence

from asyncpg import Connection, Record
class UsersQueriesMixin:
    async def get_user_by_email(self, conn: Connection, *, email: str) -> Record: ...
    async def get_user_by_username(
        self, conn: Connection, *, username: str
    ) -> Record: ...
    async def create_new_user(
        self,
        conn: Connection,
        *,
        username: str,
        email: str,
        salt: str,
        hashed_password: str
    ) -> Record: ...
    async def update_user_by_username(
        self,
        conn: Connection,
        *,
        username: str,
        new_username: str,
        new_email: str,
        new_salt: str,
        new_password: str,
        new_bio: Optional[str],
        new_image: Optional[str]
    ) -> Record: ...

class DocumentsMixin:
    async def get_tool_by_name(
        self,
            conn: Connection,
            *,
            tool_name:str
    )-> Record: ...
    async def create_new_tool(
        self,
        conn: Connection,
        *,
        tool_name: str,
    )-> Record: ...
    async def get_version_id(
        self,
        conn: Connection,
        *,
        tool_name:str,
        tool_version:str,
        )-> Record: ...
    async def create_new_version(
        self,
        conn: Connection,
        *,
        tool_name:str,
        tool_version:str,
        )-> Record: ...
    async def create_new_documents(
        self,
        conn: Connection,
        *,
        title:str,
        file_type:str,
        file_path:str,
        version_id:int,
        uploaded_by:str,
        )-> Record: ...
    async def get_document(
        self,
        conn: Connection,
        *,
        title:str,
        tool_name: str,
        tool_version: str,
        )-> Record: ...
    async def get_dft_tag(
        self,
        conn: Connection,
        *,
        tag_name:str,
        )-> Record: ...
    async def create_new_dft_tag(
        self,
        conn: Connection,
        *,
        tag_name:str,
        )-> Record: ...
    async def create_document_dft_tag(
        self,
        conn: Connection,
        *,
        documents_id:int,
        tag_name:str
        )-> Record: ...
    async def get_all_tools(
        self,
        conn: Connection,
        )-> Record: ...
    async def get_all_tool_by_id(
        self,
        conn: Connection,
        )-> Record: ...
    async def get_documents(
        self,
        conn: Connection,
        *,
        version_id:int,
        document_id:Optional[int]
        )-> Record: ...


class Queries(
    TagsQueriesMixin,
    UsersQueriesMixin,
    ProfilesQueriesMixin,
    CommentsQueriesMixin,
    ArticlesQueriesMixin,
    DocumentsMixin
): ...

queries: Queries
