"""Typings for queries generated by aiosql"""

from typing import Optional, Sequence

from asyncpg import Connection, Record
class UsersQueriesMixin:
    async def get_user_by_email(
            self,
            conn: Connection,
            *,
            email: str
    ) -> Record: ...
    async def get_user_by_username(
        self,
        conn: Connection,
        *,
        username: str
    ) -> Record: ...
    async def create_new_user(
        self,
        conn: Connection,
        *,
        username: str,
        email: str,
        salt: str,
        hashed_password: str
    ) -> Record: ...
    async def update_user_by_username(
        self,
        conn: Connection,
        *,
        username: str,
        new_username: str,
        new_email: str,
        new_salt: str,
        new_password: str,
        new_bio: Optional[str],
        new_image: Optional[str]
    ) -> Record: ...

class DocumentsMixin:
    async def get_tool_by_name(
        self,
            conn: Connection,
            *,
            tool_name:str
    )-> Record: ...
    async def create_new_tool(
        self,
        conn: Connection,
        *,
        tool_name: str,
    )-> Record: ...
    async def get_version_id(
        self,
        conn: Connection,
        *,
        tool_name:str,
        tool_version:str,
        )-> Record: ...
    async def create_new_version(
        self,
        conn: Connection,
        *,
        tool_name:str,
        tool_version:str,
        )-> Record: ...
    async def create_new_documents(
        self,
        conn: Connection,
        *,
        title:str,
        file_type:str,
        file_path:str,
        version_id:int,
        uploaded_by:str,
        )-> Record: ...
    async def get_document(
        self,
        conn: Connection,
        *,
        title:str,
        tool_name: str,
        tool_version: str,
        )-> Record: ...
    async def get_document_by_id(
        self,
        conn: Connection,
        *,
        document_id: int
    )-> Record: ...
    async def get_dft_tag(
        self,
        conn: Connection,
        *,
        tag_name:str,
        )-> Record: ...
    async def create_new_dft_tag(
        self,
        conn: Connection,
        *,
        tag_name:str,
        )-> Record: ...
    async def create_document_dft_tag(
        self,
        conn: Connection,
        *,
        documents_id:int,
        tag_name:str
        )-> Record: ...
    async def get_all_tools(
        self,
        conn: Connection,
        )-> Record: ...
    async def get_all_tool_by_id(
        self,
        conn: Connection,
        )-> Record: ...
    async def get_documents(
        self,
        conn: Connection,
        *,
        version_id:int,
        document_id:Optional[int]
        )-> Record: ...

class EmbeddingQueriesMixin:
    async def create_document_chunks(
        self,
        conn: Connection,
        *,
        document_id: int,
        context: str,
        chunk_idx: int,
        page_start: int,
        page_end: int,
        figure_refs: list[str],
        embedding: str
    ) -> Record: ...
    async def delete_document_chunks_by_document(
        self,
        conn: Connection,
        *,
        document_id: int
    ) -> None: ...
    async def create_figures(
        self,
        conn: Connection,
        *,
        img_path: str,
        document_id: int,
        figure_content: Optional[str]
    ) -> Record: ...
    async def delete_figures(
        self,
        conn: Connection,
        *,
        figure_id: int
    ) -> None: ...
    async def delete_figures_by_documents(
        self,
        conn: Connection,
        *,
        document_id: int
    ) -> None: ...
    async def get_figures(
        self,
        conn: Connection,
        *,
        figure_ids: Sequence[int]
    ) -> Sequence[Record]: ...
    async def create_chunks_figures(
        self,
        conn: Connection,
        *,
        chunks_id: int,
        figures_id: int
    ) -> None: ...
    async def get_figures_by_chunks(
        self,
        conn: Connection,
        *,
        chunks_id: Sequence[int]
    ) -> Sequence[Record]: ...
    async def get_document_chunks_by_documents(
        self,
        conn: Connection,
        *,
        document_ids: Sequence[int]
    ) -> Sequence[Record]: ...
    async def search_chunks_by_embedding(
        self,
        conn: Connection,
        *,
        query_embedding: list[float],
        top_k: int
    ) -> Sequence[Record]: ...

class Queries(
    UsersQueriesMixin,
    DocumentsMixin,
    EmbeddingQueriesMixin
): ...

queries: Queries
